# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bugshare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('url', models.URLField(max_length=100)),
                ('code', models.CharField(max_length=100000)),
                ('bug', models.CharField(blank=True, max_length=10000, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_value', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
