# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugshare',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
