# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0006_remove_bugshare_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugshare',
            name='bug',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bugshare',
            name='code',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bugshare',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
